spring:
  datasource:
    url: jdbc:mysql://localhost:3306/halwai_backend?useSSL=false
    username: root
    password: Deshna@13
spring.jpa:
  hibernate.ddl-auto: create

  cors:
    allowed-origins:
      - "http://localhost:63342"